apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- todoBackend
- todoGenerator
- todoApp
- todoBackuper
- todoBroadcaster
images:
- name: todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-app
  newTag: main-1432aa6e9af2e3e4aac0f55385f1ef7cace436c6
- name: todo-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-backend
  newTag: main-1432aa6e9af2e3e4aac0f55385f1ef7cace436c6
- name: todo-backuper
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-backuper
  newTag: main-1432aa6e9af2e3e4aac0f55385f1ef7cace436c6
- name: todo-broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-broadcaster
  newTag: main-1432aa6e9af2e3e4aac0f55385f1ef7cace436c6
- name: todo-generator
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-generator
  newTag: main-1432aa6e9af2e3e4aac0f55385f1ef7cace436c6
