apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- todoBackend
- todoGenerator
- todoApp
- todoBackuper
- todoBroadcaster
images:
- name: todo-app
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-app
  newTag: main-bd8fcf1621a7fd9c3f2f23b9969e55541efce6f3
- name: todo-backend
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-backend
  newTag: main-bd8fcf1621a7fd9c3f2f23b9969e55541efce6f3
- name: todo-backuper
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-backuper
  newTag: main-bd8fcf1621a7fd9c3f2f23b9969e55541efce6f3
- name: todo-broadcaster
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-broadcaster
  newTag: main-bd8fcf1621a7fd9c3f2f23b9969e55541efce6f3
- name: todo-generator
  newName: europe-north1-docker.pkg.dev/dwk-gke-471813/jongcp/todo-generator
  newTag: main-bd8fcf1621a7fd9c3f2f23b9969e55541efce6f3
