apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-generator
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: jonschm/todo-generator:1.1
              imagePullPolicy: IfNotPresent
              env:
                - name: TODO_BACKEND_URL
                  valueFrom:
                    configMapKeyRef:
                      name: project-config
                      key: todo_backend_url
          restartPolicy: OnFailure
