apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: image
          persistentVolumeClaim:
            claimName: todoapp-pvc
      containers:
        - name: todoapp
          image: jonschm/todoapp:1.7
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5000"
            - name: FILE_PATH
              value: /usr/src/app/images/image.png
            - name: TODO_BACKEND_URL
              value: http://todo-backend-svc:2346
            - name: EXTERNAL_TODO_APP_URL
              value: "http://localhost:8081"
          volumeMounts:
            - name: image
              mountPath: /usr/src/app/images
