apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/base
  - manifests/logOutput
  - manifests/pingpong
images:
  - name: PINGPONG/IMAGE
    newName: jonschm/pingpong:1.71
  - name: LOGOUTPUT/IMAGE
    newName: jonschm/log_output:1.7
