apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/base
  - manifests/todoBackend
  - manifests/todoGenerator
  - manifests/todoApp
  - manifests/todoBackuper
images:
  - name: todo-app
    newName: jonschm/todoapp:4.2
  - name: todo-backend
    newName: jonschm/todo-backend:4.2
  - name: todo-generator
    newName: jonschm/todo-generator:4.2
  - name: todo-backuper
    newName: jonschm/todo-backuper:4.2
