apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: config
          configMap:
            name: logoutput-config
      containers:
        - name: logoutput
          image: jonschm/log_output:1.42
          env:
            - name: PORT
              value: "5000"
            - name: INFO_FILE_PATH
              value: /usr/src/app/config/information.txt
            - name: MESSAGE
              valuefrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: message
            - name: PING_URL
              valuefrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: message
          volumeMounts:
            - name: config
              mountPath: /usr/src/app/config
              readOnly: true
