apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: exercises
data:
  postgres_user: pingponguser
  postgres_db: pingpongdb
  postgres_host: postgres-svc
  postgres_port: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: exercises
type: Opaque
stringData:
  postgres_password: myrandompassword
