name: Release application

on:
  push:
    paths:
      - "logOutput-pingpong/**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: jongcp
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish:
    if: github.event_name == 'push'
    name: Build, Publish
    runs-on: ubuntu-latest
    environment: dwk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Use gcloud CLI
        run: gcloud info

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Build and push all apps
        run: |
          cd logOutput-pingpong || exit 1
          ls -l   # check folders here
          for app in log-output pingpong; do
            echo "Checking $app folder"
            ls -l $app || exit 1
            IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$app:$BRANCH-$GITHUB_SHA
            docker build -t $IMAGE_TAG $app
          done


      - name: Commit and push updated kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'logOutput-pingpong/kustomization.yaml'
          message: "Update images to ${{ github.sha }}"
          push: true