name: Release application

on:
  push:
    paths:
      - "courseProject/**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: jongcp
  IMAGE: dwk-environments
  SERVICE: dwk-environments
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: dwk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: "Form the image name"
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and push all apps
        run: |
          cd courseProject
          for app in todoApp todo-backend todoGenerator; do
            lower_app=$(echo "$app" | tr '[:upper:]' '[:lower:]')
            IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$lower_app:$BRANCH-$GITHUB_SHA
            echo "Building $app -> $IMAGE_TAG"
            docker build -t $IMAGE_TAG $app
            docker push $IMAGE_TAG
          done

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |
          for app in todoApp todo-backend todoGenerator; do
            lower_app=$(echo "$app" | tr '[:upper:]' '[:lower:]')
            IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$lower_app:$BRANCH-$GITHUB_SHA
            kustomize edit set image $app=$IMAGE_TAG
          done
          kustomize build . | kubectl apply -f -
          for app in todoApp todo-backend todoGenerator; do
            lower_app=$(echo "$app" | tr '[:upper:]' '[:lower:]')
            kubectl rollout status deployment $lower_app
          done
          kubectl get services -o wide
