name: Release application

on:
  push:
    paths:
      - "courseProject/**"
  delete:
    branches:
      - "*"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: jongcp
  IMAGE: dwk-environments
  SERVICE: dwk-environments
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    if: github.event_name == 'push'
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    environment: dwk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Use gcloud CLI
        run: gcloud info

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: "Form the image name"
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build and push all apps
        run: |
          cd courseProject
          for app in todo-app todo-backend todo-generator; do
            IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$app:$BRANCH-$GITHUB_SHA
            echo "Building $app -> $IMAGE_TAG"
            docker build -t $IMAGE_TAG $app
            docker push $IMAGE_TAG
          done

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |
          cd courseProject

          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          if [ "$BRANCH_NAME" = "main" ]; then
            NAMESPACE=project
          else
            NAMESPACE=$BRANCH_NAME
          fi

          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          kustomize edit set namespace $NAMESPACE

          for app in todo-app todo-backend todo-generator; do
            IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$app:$BRANCH-$GITHUB_SHA
            kustomize edit set image $app=$IMAGE_TAG
          done
          kustomize build . | kubectl apply -f -
          for app in todo-app todo-backend; do
            kubectl rollout status deployment $app
          done
          kubectl get services -o wide

  delete:
    if: github.event_name == 'delete'
    runs-on: ubuntu-latest
    environment: dwk
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: Delete namespace
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "Deleting namespace project"
            kubectl delete namespace project
          else
            echo "Deleting namespace ${GITHUB_REF_NAME}"
            kubectl delete namespace ${GITHUB_REF_NAME} --ignore-not-found
          fi
